include current-theme.conf

# Font
font_family JetBrainsMono Nerd Font Mono
font_size 14.0

# Window settings
remember_window_size  no
initial_window_width  960
initial_window_height 720

window_padding_width 5 10

background_opacity 0.8

background_blur 1

# Windows layout
enabled_layouts splits,stack

sync_to_monitor yes
repaint_delay 8
input_delay 1

# Split windows
map ctrl+shift+left_bracket launch --location=hsplit --cwd=current
map ctrl+shift+right_bracket launch --location=vsplit --cwd=current

# Windows navigation
map ctrl+shift+left neighboring_window left
map ctrl+shift+h neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+l neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+j neighboring_window up
map ctrl+shift+down neighboring_window down
map ctrl+shift+k neighboring_window down

# Close windows/tabs
map ctrl+shift+q close_window
map ctrl+shift+w close_tab

# Zoom
map ctrl+shift+z toggle_layout stack

