include current-theme.conf

font_family JetBrainsMono Nerd Font Mono
font_size 14.0

remember_window_size  no
initial_window_width  960
initial_window_height 720

window_padding_width 5 10

background_opacity 0.8

background_blur 1

